"""empty message

Revision ID: 022092584d97
Revises: bf99a92c9ba0
Create Date: 2021-06-19 17:38:06.257389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '022092584d97'
down_revision = 'bf99a92c9ba0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment', sa.Column('schedule', sa.String(length=50), nullable=False))
    op.add_column('appointment', sa.Column('via', sa.String(length=50), nullable=False))
    op.drop_column('appointment', 'start_date')
    op.drop_column('appointment', 'end_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment', sa.Column('end_date', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('appointment', sa.Column('start_date', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('appointment', 'via')
    op.drop_column('appointment', 'schedule')
    # ### end Alembic commands ###
