"""empty message

Revision ID: bf99a92c9ba0
Revises: e15ab348c31b
Create Date: 2021-06-14 11:07:11.932593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf99a92c9ba0'
down_revision = 'e15ab348c31b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'is_profesional')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('is_profesional', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
