"""empty message

Revision ID: cb4b29c02fec
Revises: 
Create Date: 2021-06-09 19:11:37.554187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb4b29c02fec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('hased_password', sa.String(length=240), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('is_profesional', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('appointment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('day_date', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.String(length=50), nullable=False),
    sa.Column('end_date', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('profesional_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['profesional_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('diagnostic', sa.String(length=240), nullable=True),
    sa.Column('progress', sa.String(length=240), nullable=True),
    sa.Column('finished', sa.String(length=240), nullable=True),
    sa.Column('bitacora', sa.String(length=240), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('profesional_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['profesional_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report')
    op.drop_table('appointment')
    op.drop_table('person')
    # ### end Alembic commands ###
