"""empty message

Revision ID: e15ab348c31b
Revises: cb4b29c02fec
Create Date: 2021-06-10 10:03:17.050087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e15ab348c31b'
down_revision = 'cb4b29c02fec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('salt', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'salt')
    # ### end Alembic commands ###
